services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  chatwoot:
    image: chatwoot/chatwoot
    container_name: chatwoot
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - "3000:3000"

  evolution-api:
    image: limewire/evolution-api
    container_name: evolution-api
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "4000:4000"

volumes:
  postgres_data:
  redis_data:
